### ISSUE TITLE
Add ALM to Persian/Arabic layouts

### ISSUE THREAD

**Issue by r12a** [r12a/pickers#10]
From Behnam

Background: http://unicode.org/L2/L2011/11432r-n4180r-alm-form.pdf

**Comment by behnam** [comment]
Some historic background:

* Proposal to encode an Arabic-Letter Mark (ALM)
  http://unicode.org/L2/L2011/11278-arabic-letter-mark.pdf

* Proposal to encode the Arabic Letter Mark (ALM)
  http://unicode.org/L2/L2011/11432r-n4180r-alm-form.pdf

* Reconciling Script and Script_Extensions
  http://www.unicode.org/L2/L2013/13240-predominant-script.pdf

* Script property of Arabic Letter Mark and interaction with digit substitution mechanisms
  http://unicode.org/L2/L2016/16306-alm-script-prop.pdf

**Comment by r12a** [comment]
fixed for persian in https://github.com/r12a/pickers/commit/b6a1029f278c846f67cae5d731d6b40e87ceb0c5

**Comment by r12a** [comment]
fixed for arabic in https://github.com/r12a/pickers/commit/03b1eaa6243821eb3aad1dc11933f6fca843c392

**Comment by r12a** [comment]
fwiw, i wrote up a description at https://r12a.github.io/scripts/arabic/block#char061C
