### ISSUE TITLE
[cherokee picker] Add diacritics

### ISSUE THREAD

**Issue by moyogo** [r12a/pickers#31]
http://www.unicode.org/L2/L2014/14064r-n4537r-cherokee.pdf notes that U+0323 COMBINING DOT BELOW indicates shifts in consonant readings (voiced to voiceless or the opposite), U+0331 COMBINING MACRON BELOW indicates dropping of a vowel, U+0324 COMBINING DIAERESIS BELOW indicates both shifts in consonante readings and dropping of a vowel, and U+0330 COMBINING TILDE BELOW exceptionally indicates nasalization. Furthermore tone marks above a letter indicate pitch in technical transcription, following IPA conventions: U+0304 COMBINING MACRON for mid tone, U+0302 COMBINING CIRCUMFLEX ACCENT for falling tone, U+030C COMBINING CARON for rising tone, U+0300 COMBINING GRAVE ACCENT for low tone, U+0301 COMBINING ACUTE ACCENT for high tone and U+030B COMBINING DOUBLE ACUTE ACCENT for super high tone.

**Comment by r12a** [comment]
That's useful, thanks.  I'll make appropriate changes when i get a spare moment.

**Comment by r12a** [comment]
New section added in https://github.com/r12a/scripts/commit/c3b4b40a9f8889d4cceefadf1eb32fa767555386

Tone marks mentioned higher up.

Diacritics also added to the picker. (Note tone marks.)

**Comment by moyogo** [comment]
Thank you!
