### ISSUE TITLE
[ipa picker] Add the variant tone letters

### ISSUE THREAD

**Issue by szc126** [r12a/pickers#39]
I think it would be nice if this tool also had the reversed tone letters and the dotted tone letters (found in Modifier Tone Letters), for Sinologists.

**Comment by r12a** [comment]
Fixed by https://github.com/r12a/pickers/commit/f0f8656c5a0ea21f91cad672b0dc89ea11dd7a84#diff-4493bbb16f6dc547b6ea6feea7ecbd6a.

Click on "Show more tone marks" near the bottom of the selection area.

hth
