### ISSUE TITLE
[arabicblock picker] Buggy old Arabic font

### ISSUE THREAD

**Issue by dscorbett** [r12a/pickers#41]
The default font for Arabic, scheherazaderegotwebfont.woff2, has a bug where U+06BA ARABIC LETTER NOON GHUNNA has dots in some forms. It should be updated to the latest version of Scheherazade, in which that bug has been fixed.

**Comment by r12a** [comment]
Thanks, fixed by https://github.com/r12a/shared/commit/cd670bfac8fefb8ef00159ddf605cb99a4f369e9
