### ISSUE TITLE
[bengali picker]  conjunct letter subscript/diacritic missing

### ISSUE THREAD

**Issue by emthaut** [r12a/pickers#43]
Thanks for the great work.

After your last update for the Bengali picker, the conjunct letter subscript/diacritic disappeared so that we can't combine two letters together. Like প্রিয় versus পরিয়
Now there's only an option to add a dot above the letters. Normally it's a \ type subscript that should be in its place.

Thanx

**Comment by r12a** [comment]
@emthaut thanks very much for spotting that oversight! I rebuilt the picker using the Tamil picker as a template, and forgot to replace the virama. Should now be fixed. Let me know if you still have problems.
