### ISSUE TITLE
[khmer picker]  Please add ZWJ and ZWNJ

### ISSUE THREAD

**Issue by olivierberten** [r12a/pickers#44]
ZWJ and ZWNJ are necessary for typing some unusual orthography.

**Comment by r12a** [comment]
@olivierberten i'm happy to add those, but can you give me some examples of where they are used?

**Comment by olivierberten** [comment]
http://www.unicode.org/versions/Unicode11.0.0/ch16.pdf#page=28

**Comment by r12a** [comment]
Ah, i had forgotten about that. I added them.

(I'm not seeing a font on my MacOS system that actually does what the Unicode Standard says, though.  Are you having success?)

**Comment by olivierberten** [comment]
You should try with the [Khmer Mondulkiri](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=Mondulkiri) font family (which you could add as webfont as well since it's OFL)

**Comment by olivierberten** [comment]
And for the វិវីវឹវឺកិកីកឹកឺគិគីគឹគឺតិតីតឹតឺភិភីភឹភឺ ligatures, Khmer OS Muol is among the very few to have them.

**Comment by r12a** [comment]
Khmer Mondulkiri/Busra added as selections (not yet webfonts).

However, i'm seeing no difference between text with or without ZWNJ (on MacOS).
http://r12a.github.io/pickers/khmer/?text=%E1%9E%94%E2%80%8C%E1%9F%8A%E1%9E%B8%E1%9E%99%E1%9F%82%E1%9E%9A%0A%E1%9E%94%E1%9F%8A%E1%9E%B8%E1%9E%99%E1%9F%82%E1%9E%9A

**Comment by olivierberten** [comment]
Indeed... I guess it's because of the khmer rule that says

> Triisap always remains in its original shape as superscript after Ba (ប), even if it
is followed by a superscript vowel in order to enable the distinction between ប៊ិ and ប៉ិ (the latter using Muusikatoan).

(see http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=Mondulkiri-5.513-Ortho&filename=Mondulkiri-5.513-Ortho.pdf at page 6)

The other example works though: https://r12a.github.io/pickers/khmer/?text=%E1%9E%94%E1%9F%92%E1%9E%9A%E1%9E%8F%E1%9E%BA%E1%9E%84%E1%9E%A2%E1%9F%8A%E1%9E%B9%E1%9F%87%0A%E1%9E%94%E1%9F%92%E1%9E%9A%E1%9E%8F%E1%9E%BA%E1%9E%84%E1%9E%A2%E2%80%8C%E1%9F%8A%E1%9E%B9%E1%9F%87 (with Khmer OS Battambang as well)

**Comment by olivierberten** [comment]
According to this page: https://marc.durdin.net/2017/03/when-nyam-meets-nyam/ on OS X Sierra ប‌៊ី should work as expected by the Unicode standard, not sure about the zwnj version, though...

**Comment by r12a** [comment]
ZWJ and ZWNJ are now available at https://r12a.github.io/pickers/khmer/

I''ll leave this open to remind me to document in my notes the info you point to in the above links.

**Comment by r12a** [comment]
Somehow, the latest version of the Khmer picker had lost the ZW(N)J keys.  These have now been added back with also 1/6EM SPACE and EM SPACE (for Krung and Tampuan). See https://r12a.github.io/pickers/khmr/

Also some mentions of ZW(N)J were added to https://r12a.github.io/scripts/khmer/ (although some additional text may be added later).
