### ISSUE TITLE
[cyrillic picker]  Missing Characters

### ISSUE THREAD

**Issue by alex-cres** [r12a/pickers#48]
Ў and ў are missing from the picker.
Ў - U+040E CYRILLIC CAPITAL LETTER SHORT U
ў - U+045E CYRILLIC SMALL LETTER SHORT U

**Comment by r12a** [comment]
Thanks for the comment. Fixed in https://github.com/r12a/pickers/commit/5b2551d116d8847b6c54ae2f23955e705bbef88e
