### ISSUE TITLE
[arabicblock picker] Arabic Extended-A

### ISSUE THREAD

**Issue by LornaSIL** [r12a/pickers#54]
It would be nice if you could add in the Arabic Extended-A characters. I tried to find U+08AE and U+08A0 and neither one of them are showing up in the picker.
Thanks for considering this.

**Comment by r12a** [comment]
Done!  You caught me at just the right moment.

I only added the letters so far. I need more time to work on the diacritics, but if you're desperate for some of those let me know.

I also tidied a bit and made the selection glyphs multiline, so it's easier to spot stuff. The breaks are generally where ijam begin appearing on the other side or both sides of the base character.

I also fixed a bug.  When you switch the layout direction of the selection area it now really does reorder the arabic characters.

Commit is here: https://github.com/r12a/pickers/commit/cd000799b172dd3030ab469336287c5085cccba8

**Comment by LornaSIL** [comment]
Very nice. Thanks so much!
