### ISSUE TITLE
[javanese picker]  ADD TITLE HERE

### ISSUE THREAD

**Issue by GarrettKam** [r12a/pickers#57]
The Javanese symbol ꧀ for removing the vowel to create the next subscript character does not work.

**Comment by r12a** [comment]
@GarrettKam can you give me some specifics about what doesn't work?  Is clicking on the selection panel not working, or is it that you are not seeing the expected behaviour after the character appears in the edit box?

**Comment by GarrettKam** [comment]
When I use the sign to remove the vowel sound directly after a letter without a space after it, the subform of the next letter should appear but it does not. 

Sent from Yahoo Mail on Android 
 
  On Thu, 27 Jun 2019 at 17:40, r12a<notifications@github.com> wrote:   
@GarrettKam can you give me some specifics about what doesn't work? Is clicking on the selection panel not working, or is it that you are not seeing the expected behaviour after the character appears in the edit box?

**Comment by r12a** [comment]
Having not heard more, i'll assume that this is now fixed.  Please reopen if still an issue, but provide sample text to try.
