### ISSUE TITLE
[ipa char app]  Copy function broken

### ISSUE THREAD

**Issue by emthaut** [r12a/pickers#58]
Hi,
Great picker charts, but it seems like after recent updates that copy function is no longer possible, at least no on the IPA and Bengali pickers.

**Comment by r12a** [comment]
Thanks for the feedback. I'm not seeing this issue myself.  What OS are you using? Could you step me through what you did, and where it went wrong?

**Comment by emthaut** [comment]
I click/prepare a text and then highlight it, but when I press Ctrl-C (Windows) to copy it, a 'c' appears/is types in, and the text isn't copied so that I can paste it elsewhere.

Actually, it's the Ctrl that creates the 'c' from the highlighted text. And the Alt key types in a 'a'.

**Comment by r12a** [comment]
Thanks for the extra information. That looks like a Windows-specific bug (no problems on my Mac). I'll check it out. In the meantime, you may want to click on the 'Copy to clipboard' icon to the left just above the text area. It's not as convenient, but should help until i can fix the key capture.

**Comment by r12a** [comment]
@emthaut i'm hopeful that this bug is now fixed. See https://github.com/r12a/pickers/issues/60#issuecomment-584780597

**Comment by r12a** [comment]
Feel free to reopen this if still problematic.
