### ISSUE TITLE
[ipa char app]  Missing consonants in selection area

### ISSUE THREAD

**Issue by mfaytak** [r12a/pickers#59]
About half of the consonants in the selection area are newly missing - there one day, gone the next. The characters do not display, and they are additionally not clickable for input into the text box.

Attached image is what I see on Chrome 79.0.3945.79 (Official Build) (64-bit) on a Mac running OS 10.14.5. Notice that all voiceless consonants (i.e. the leftmost items in their "cells" in the IPA consonant table) are missing.

On my box and another device, the issue replicates in Firefox v 72.0.2 and Safari 12.1.1.

![image](https://user-images.githubusercontent.com/12757610/73416740-bffbd200-42ca-11ea-83a3-44ffc2645f25.png)

**Comment by r12a** [comment]
Many thanks for reporting this!  It was an unexpected side effect of some changes i committed yesterday. Should be fixed now.  Please let me know if you still have a problem.

**Comment by mfaytak** [comment]
Looks to be fixed on the aforementioned Chrome/Firefox/Safari versions. Thanks for maintaining such a useful tool!
