### ISSUE TITLE
[ipa2] [ipa3] enhancement: "alternative charts" should be available on all 3

### ISSUE THREAD

**Issue by drammock** [r12a/pickers#65]
The "alternative charts" toggle disappears after selecting one of the alternatives.  I noticed that it redirects to a different URL (`.../ipa2/` or `.../ipa3/`), so I realize I can get back to the original chart via browser back navigation.  But I think it's a little more friendly if all 3 versions had the "alternative charts" option in the UI.

**Comment by r12a** [comment]
Done (finally) at https://github.com/r12a/pickers/commit/d2acb3e3c23cac829acc4ccc6d8355f7bc0aa5e5#diff-be68fbcf4bc6eabe90f3bbcc95f50ea3ebc7bb539030eec1e9f80089337b4963

**Comment by drammock** [comment]
nice!  Thanks @r12a
