### ISSUE TITLE
[ipa]  Ctrl not working in IPA pickers

### ISSUE THREAD

**Issue by paulwarren** [r12a/pickers#68]
For some reason Ctrl has stopped working in IPA pickers, so if I try to copy a character sequence from the main window with ctrl-c it just replaces the text with c

**Comment by r12a** [comment]
Paul, can you do a hard refresh of the page (shift + reload).  Hopefully that will fix it.  You may have downloaded a half-baked version i put out briefly, but should now be fixed.

**Comment by paulwarren** [comment]
Thanks for the prompt reply - that did not work. After sending off my issue comment I dug around in the solved issues and found that I needed to switch off type assist. This does fix it, although it looks like I need to do this each time I launch the app. BTW, it is showing that I am using v27, if this is any help.

**Comment by r12a** [comment]
Thanks.  It's a bit too late here for me to investigate further, so i'll get on it again tomorrow morning.  What browser and device are you using? And which of the 3 IPA pickers?

**Comment by paulwarren** [comment]
I am on a Windows PC (x64, Windows 10.0.19043). I'm not sure how to tell which IPA picker I am using, but the info at the top has r12a >> apps >> IPA standard v27

**Comment by r12a** [comment]
Ok. So it's the original IPA picker.  Looks like i'll need to test it on a Windows machine.  Works fine for me on the Mac.  What browser are you using?

**Comment by paulwarren** [comment]
Chrome  93.0.4577.63

**Comment by r12a** [comment]
Hopefully, this should now be fixed.  If not, let me know.  Sorry for the disturbance.

**Comment by paulwarren** [comment]
All good now. Thank you!
