### ISSUE TITLE
[maka]  Add Noto Serif Makasar

### ISSUE THREAD

**Issue by mahalisyarifuddin** [r12a/pickers#71]
Just found out that [Noto Serif Makasar](https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSerifMakasar) was already made. Would be great if the font is added to the picker.

Thank you.

**Comment by r12a** [comment]
Ah!  That had also passed me by.  Thanks for the poke!

I have now updated the app to use the noto font by default.  You may need to do a hard refresh and click on Reset:GO to update your client.

https://r12a.github.io/pickers/maka/
